test for errors

diff --git a/.github/workflows/python-package.yml b/.github/workflows/python-package.yml
--- a/.github/workflows/python-package.yml
+++ b/.github/workflows/python-package.yml
@@ -40,6 +40,7 @@ jobs:
         run: |
           cd tests
           pytest test_login.py -s -q -x --dashboard --html=report.html --save-screenshot --maximize  2>&1 | tee result.log   
+          pytest_exit_code=${PIPESTATUS[0]}  # Capture the exit code of pytest
 
 
       - name: Send logs to Slack
@@ -49,7 +50,7 @@ jobs:
           log_contents=$(cat tests/result.log | sed 's/"/\\"/g' | sed ':a;N;$!ba;s/\n/\\n/g')
           
           # Check for test result (look for "PASSED" or "FAILED")
-          if grep -q "passed" tests/result.log; then
+          if [[ $pytest_exit_code -eq 0 ]]; then
             result_summary="*Test Results Summary:* Passed ✅"
           else
             result_summary="*Test Results Summary:* Failed ❌"
