update the artifacts that sent to slack

diff --git a/.github/workflows/python-package.yml b/.github/workflows/python-package.yml
--- a/.github/workflows/python-package.yml
+++ b/.github/workflows/python-package.yml
@@ -65,6 +65,24 @@ jobs:
         run: |
           zip -r test-results.zip tests/report.html tests/assets/
 
+      - name: Get Upload URL from Slack
+        run: |
+          UPLOAD_URL=$(curl -X POST \
+            -H "Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}" \
+            -H "Content-Type: application/json" \
+            --data '{"file_name":"test-results.zip","channels":["${{ secrets.SLACK_CHANNEL_ID }}"]}' \
+            https://slack.com/api/files.getUploadURLExternal | jq -r '.url')
+
+      - name: Upload ZIP to Slack
+        run: |
+          curl -X POST \
+            -H "Content-Type: multipart/form-data" \
+            -F file=@test-results.zip \
+            -F filename="test-results.zip" \
+            -F channels="${{ secrets.SLACK_CHANNEL_ID }}" \
+            -F filetype="zip" \
+            $UPLOAD_URL
+
       - name: Send results to Slack with the zip file
         if: success() || failure()  # Send notification regardless of success/failure
         run: |
@@ -74,44 +92,26 @@ jobs:
             }' \
             ${{ secrets.SLACK_CHANNEL_REPORT_HOOK }}
 
-      - name: Upload ZIP file to Slack
-        if: success() || failure()  # Send notification regardless of success/failure
-        run: |
-          # Step 1: Get the upload URL from Slack using files.getUploadURLExternal
-          RESPONSE=$(curl -X POST https://slack.com/api/files.getUploadURLExternal \
-            -H 'Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}' \
-            -H 'Content-Type: application/json' \
-            -d '{
-                  "channels": ["'${{ secrets.SLACK_TEST_REGRESSIONAL_CHANNEL_ID }}'"]
-                }')
-          
-          echo "Response from Slack: $RESPONSE"
-          
-          # Extract the URL from the response
-          UPLOAD_URL=$(echo "$RESPONSE" | jq -r .url)
-          
-          # Check if the URL is valid
-          if [[ -z "$UPLOAD_URL" || "$UPLOAD_URL" == "null" ]]; then
-            echo "Error: Failed to get a valid upload URL from Slack."
-            exit 1
-          fi
-          
-          # Step 2: Upload the file using the obtained URL
-          curl -X POST $UPLOAD_URL \
-            -F file=@test-results.zip \
-            -F "filename=test-results.zip" \
-            -F "filetype=zip"
-          
-          # Step 3: Complete the upload and add the initial comment
-          curl -X POST https://slack.com/api/files.completeUploadExternal \
-            -H 'Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}' \
-            -H 'Content-Type: application/json' \
-            -d '{
-                  "file": "'"$UPLOAD_URL"'",
-                  "initial_comment": "Test results are available! :tada:\n\nHere is the [test report](https://github.com/jeremyyymrcs/Login-API-Automation/actions/runs/${{ github.run_id }})\n\nThe tests have completed. Check the results and logs.\n\nAlso, the zip file containing the results is attached below."
-                }'
-
-
+#      - name: Send results to Slack with the zip file
+#        if: success() || failure()  # Send notification regardless of success/failure
+#        run: |
+#          curl -X POST -H 'Content-type: application/json' \
+#            --data '{
+#              "text": "Test results are available! :tada:\n\nHere is the [test report](https://github.com/jeremyyymrcs/Login-API-Automation/actions/runs/${{ github.run_id }})\n\nThe tests have completed. Check the results and logs.\n\nAlso, the zip file containing the results is attached below."
+#            }' \
+#            ${{ secrets.SLACK_CHANNEL_REPORT_HOOK }}
+#
+#      - name: Upload ZIP file to Slack
+#        if: success() || failure()  # Send notification regardless of success/failure
+#        run: |
+#          # Upload the zip file to Slack channel using the new recommended method
+#          curl -X POST https://slack.com/api/files.getUploadURLExternal \
+#            -H 'Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}' \
+#            -F file=@test-results.zip \
+#            -F "initial_comment=Test results are available! :tada:\n\nHere is the [test report](https://github.com/jeremyyymrcs/Login-API-Automation/actions/runs/${{ github.run_id }})\n\nThe tests have completed. Check the results and logs.\n\nAlso, the zip file containing the results is attached below." \
+#            -F channels=${{ secrets.SLACK_TEST_REGRESSIONAL_CHANNEL_ID }} \
+#            -F "filename=test-results.zip" \
+#            -F "filetype=zip"
 
 
 #
